name: Build and Publish Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: vaultwarden-argon2
      GHCR: ghcr.io
      GHCR_IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: "junkurihara/vaultwarden"
          path: "./"
          ref: "bcc215241244ba77e47fe37c1a64dc7cc8b367af"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.GHCR }}/${{ env.GHCR_IMAGE_NAME }}:latest
          file: ./Dockerfile
